server:
  port: 8771
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: give
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 1000
      min-idle: 1
      max-active: 10000
      max-wait: -1
    #数据库连接信息
  datasource:
    name: test
    url: jdbc:mysql://119.23.74.128:3306/pets?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 6000000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 6000000
    minEvictableIdleTimeMillis: 30000000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    ##activemq连接信息
  activemq:
    broker-url: tcp://119.23.74.128:61616
    in-memory: true
    pool:
      enabled: false
mybatis:
  mapper-locations: classpath:spring/*.xml
  type-aliases-package: com.zkt.dao
##队列messages:queue: email_queue